### ISSUE TITLE
SDK error for Oauth regarding "state" parameter?

### ISSUE THREAD

**Issue by aarcher11** [ciscospark/spark-js-sdk#414]
Receive the following error when trying to use the SDK function:

`ciscospark.credentials.buildOAuthUrl() in order to redirect to Cisco Spark login page:
TypeError: Cannot read property 'state' of undefined
   at buildOAuthUrl (/Users/taylorhanson/Downloads/node_modules/ciscospark/node_modules/@ciscospark/spark-core/dist/plugins/credentials/credentials/common.js:473:34)
   at /Users/taylorhanson/Downloads/SparkPlay.js:66:33
   at Layer.handle [as handle_request] (/Users/taylorhanson/Downloads/node_modules/express/lib/router/layer.js:95:5)
   at next (/Users/taylorhanson/Downloads/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/Users/taylorhanson/Downloads/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/Users/taylorhanson/Downloads/node_modules/express/lib/router/layer.js:95:5)
   at /Users/taylorhanson/Downloads/node_modules/express/lib/router/index.js:277:22
   at Function.process_params (/Users/taylorhanson/Downloads/node_modules/express/lib/router/index.js:330:12)
   at next (/Users/taylorhanson/Downloads/node_modules/express/lib/router/index.js:271:10)
   at /Users/taylorhanson/Downloads/SparkPlay.js:36:5`

Tried setting process.env.CISCOSPARK_STATE = "abcde" but did not help.
https://ciscospark.github.io/spark-js-sdk/example/servers/ This page does not seem to provide any useful information.

**Comment by ianwremmel** [comment]
pass an empty object to buildOAuthUrl
